### ISSUE TITLE
Namespace L has no exported member MarkerClusterGroup

### ISSUE THREAD

**Issue by siyanew** [Asymmetrik/angular2-leaflet-markercluster#6]
When I use markerClusterReady I got this error :

```ERROR in /Users/siyanew/Visualizer/Visualizer/src/app/app.component.ts (77,39): Namespace 'L' has no exported member 'MarkerClusterGroup'.```

What can I do ?

**Comment by reblace** [comment]
This is usually a typings or dependency error. You probably just need to ensure you've installed the typings for the markercluster plugin:

```npm install @types/leaflet.markercluster```

Note that they recently renamed the typings from ```leaflet-markercluster``` to ```leaflet.markercluster```

Also, make sure you're actually importing leaflet and leaflet-markercluster. You can check out the demo code as a reference:

- https://github.com/Asymmetrik/angular2-leaflet-markercluster/blob/master/src/demo/vendor.ts
- https://github.com/Asymmetrik/angular2-leaflet-markercluster/blob/master/src/demo/app/leaflet-markercluster/markercluster-demo.component.ts

If you're still having the issue, it might be useful to know some of your details:
- What OS you're on (some Windows people seem to have issues with typings)
- What framework you're using (angular cli?, straight webpack, etc) and what version
- What version of typescript you're running
- Anything else unusual about your setup?

Typings issues usually aren't related to the plugin itself, but rather some misconfiguration of the Typescript setup of your project. But, I can try to provide some insight if you provide these details. Thanks for using the plugin!

**Comment by siyanew** [comment]
Thanks a million ... you made my day 💪

**Comment by reblace** [comment]
I'm gonna assume you're good. Thanks for using the plugin!

**Comment by brintal** [comment]
@reblace Thanks so much for your hint about the renaming from leaflet-markercluster to leaflet.markercluster. Solved my issues as well!

**Comment by prem2017** [comment]
@reblace 

I did all you said but I get this error:

```
NullInjectorError: R3InjectorError(DynamicTestModule)[ActivatedRoute -> ActivatedRoute]: 
	  NullInjectorError: No provider for ActivatedRoute!
	    at NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:1085:1)
	    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:16968:1)
	    at R3Injector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:16968:1)
	    at NgModuleRef$1.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:36342:1)
	    at Object.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:33985:1)
	    at getOrCreateInjectable (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:5848:1)
	    at ɵɵdirectiveInject (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:21116:1)
	    at NodeInjectorFactory.ErrMapUriComponent_Factory [as factory] (ng:///ErrMapUriComponent/ɵfac.js:5:46)
	    at getNodeInjectable (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:5993:1)
	    at instantiateRootComponent (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:12832:1)
	Expected undefined to be truthy.


```

Before adding this `import 'leaflet.markercluster';` I was getting the following error:

```L has no exported member MarkerClusterGroup```

I do not know what to do. Please help.

**Comment by tseringn** [comment]
same here, getting the error in 2023

**Comment by varshakharenatpower** [comment]
I am still getting the error.
